Repository MarlonLira/simpleparking, pull requests merged in 2020-11, with the labels that each got.

#59 ajustes no fluxo
  src/app/app.module.ts
  src/app/base.component.ts
  src/app/commons/core/utils.ts
  src/app/commons/enums/authentication.ts
  src/app/components/auth/auth.component.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/employee/employee.component.ts
  src/app/components/parking-product/parking-product-list/parking-product-list.component.html
  src/app/components/parking-product/parking-product.component.ts
  src/app/components/parking-space/parking-space-list/parking-space-list.component.html
  src/app/components/parking-space/parking-space.component.ts
  src/app/components/parking/parking.component.ts
  src/app/components/scheduling-product/scheduling-product-list/scheduling-product-list.component.css
  src/app/components/scheduling-product/scheduling-product-list/scheduling-product-list.component.html
  src/app/components/scheduling-product/scheduling-product-list/scheduling-product-list.component.spec.ts
  src/app/components/scheduling-product/scheduling-product-list/scheduling-product-list.component.ts
  src/app/components/scheduling-product/scheduling-product-view-dialog/scheduling-product-view-dialog.component.css
  src/app/components/scheduling-product/scheduling-product-view-dialog/scheduling-product-view-dialog.component.html
  src/app/components/scheduling-product/scheduling-product-view-dialog/scheduling-product-view-dialog.component.spec.ts
  src/app/components/scheduling-product/scheduling-product-view-dialog/scheduling-product-view-dialog.component.ts
  src/app/components/scheduling-product/scheduling-product.component.css
  src/app/components/scheduling-product/scheduling-product.component.html
  src/app/components/scheduling-product/scheduling-product.component.spec.ts
  src/app/components/scheduling-product/scheduling-product.component.ts
  src/app/components/scheduling/scheduling-list/scheduling-list.component.html
  src/app/components/scheduling/scheduling.component.ts
  src/app/services/employee.service.ts
  src/app/services/parking-product.service.ts
  src/app/services/parking-score.service.ts
  src/app/services/parking-space.service.ts
  src/app/services/scheduling.service.ts
  src/app/shared/navbar/navbar.component.css
  src/app/shared/navbar/navbar.component.html
  src/app/shared/navbar/navbar.component.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#60 Fix(SIGNUP): Criação do Scheduling Product
  src/app/app.routing.ts
  src/app/components/scheduling/scheduling-view-dialog/scheduling-view-dialog.component.html
  src/app/components/scheduling/scheduling-view-dialog/scheduling-view-dialog.component.ts
  src/app/models/scheduling.model.ts
  src/app/services/scheduling.service.ts
  src/app/shared/sidebar/sidebar.component.ts
Labels: enhancement

#61 fix(app.routing)
  src/app/app.routing.ts
Labels: bug

#63 fix(parkingSelect)
  src/app/shared/navbar/navbar.component.css
  src/app/shared/navbar/navbar.component.html
  src/app/shared/navbar/navbar.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/sidebar/sidebar.component.css
  src/app/shared/sidebar/sidebar.component.html
  src/app/shared/sidebar/sidebar.component.ts
Labels: enhancement

#64 fix(parking_product): ajustes no grid
  src/app/components/employee/employee-profile/employee-profile.component.ts
  src/app/components/parking-product/parking-product-list/parking-product-list.component.html
  src/app/components/parking-product/parking-product-list/parking-product-list.component.ts
  src/app/components/parking-product/parking-product.component.ts
  src/app/components/parking-space/parking-space-list/parking-space-list.component.html
  src/app/components/settings/settings.component.ts
  src/app/services/parking-product.service.ts
  src/app/shared/parkings-select/parkings-select.component.css
  src/app/shared/parkings-select/parkings-select.component.html
  src/app/shared/parkings-select/parkings-select.component.spec.ts
  src/app/shared/parkings-select/parkings-select.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/sidebar/sidebar.component.css
  src/app/shared/sidebar/sidebar.component.html
  src/app/shared/sidebar/sidebar.component.ts
Labels: enhancement

#65 fix(parking_select): ajustes referentes a tela de celular
  package.json
  src/app/components/scheduling/scheduling-view-dialog/scheduling-view-dialog.component.ts
  src/app/services/parking-promotion.service.spec.ts
  src/app/services/parking-promotion.service.ts
  src/app/shared/navbar/navbar.component.ts
  src/app/shared/parkings-select/parkings-select.component.html
  src/assets/css/layout.css
Labels: bug

#66 style(this): ajustes no visual e correções de logica
  src/app/base.component.ts
  src/app/components/employee/employee-form/employee-form.component.html
  src/app/components/maps/maps.component.ts
  src/app/components/parking-product/parking-product-form/parking-product-form.component.html
  src/app/components/parking-product/parking-product.component.ts
  src/app/components/parking-space/parking-space-form/parking-space-form.component.html
  src/app/components/parking/parking-form/parking-form.component.ts
  src/app/components/parking/parking.component.ts
  src/app/components/settings/settings-list/settings-list.component.html
Labels: bug

#68 Fix master
  package-lock.json
  src/app/app.routing.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/scheduling/scheduling-view-dialog/scheduling-view-dialog.component.html
  src/app/components/scheduling/scheduling-view-dialog/scheduling-view-dialog.component.ts
  src/app/consts.ts
  src/app/services/scheduling.service.ts
Labels: bug, enhancement

#70 Parking price new
  src/app/components/parking-price/parking-price-form/parking-price-form.component.html
  src/app/components/parking-price/parking-price-form/parking-price-form.component.ts
  src/app/components/parking-price/parking-price.component.ts
  src/app/shared/sidebar/sidebar.component.ts
Labels: enhancement

#73 Gustavo
  src/app/components/employee/employee.component.ts
  src/app/components/parking-space/parking-space.component.ts
Labels: enhancement

#74 Gustavo
  src/app/components/employee/employee.component.ts
  src/app/components/parking-price/parking-price-form/parking-price-form.component.html
Labels: bug, enhancement

#77 Fix bugs
  package-lock.json
  package.json
  src/app/components/employee/employee-form/employee-form.component.ts
  src/app/components/employee/employee.component.ts
  src/app/components/parking-space/parking-space-form/parking-space-form.component.html
  src/app/shared/navbar/navbar.component.html
  src/assets/.gitkeep
  src/assets/css/demo.css
Labels: bug
